spring.application.name=Spendwise

# Use environment variables for DB connection
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
spring.datasource.driver-class-name=${DEV_DB_DRIVER}


# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${DEV_HIBERNATE_DIALECT}

# JWT secret
jwt.secret=${JWT_SECRET}

# App URLs
app.frontend.url=${FRONTEND_URL}
app.activation.url=${ACTIVATION_URL}

# Mail configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Path
server.servlet.context-path=/api/v1.0

# Active profile
spring.profiles.active=dev

